In [1]:
import pandas as pd
import json

In [2]:
big_dataset = pd.read_csv("tcc_ceds_music.csv")

In [3]:
big_dataset

,Unnamed: 0,artist_name,track_name,release_date,genre,lyrics,len,dating,violence,world/life,...,sadness,feelings,danceability,loudness,acousticness,instrumentalness,valence,energy,topic,age
0,0,mukesh,mohabbat bhi jhoothi,1950,pop,hold time feel break feel untrue convince spea...,95,0.000598,0.063746,0.000598,...,0.380299,0.117175,0.357739,0.454119,0.997992,0.901822,0.339448,0.137110,sadness,1.000000
1,4,frankie laine,i believe,1950,pop,believe drop rain fall grow believe darkest ni...,51,0.035537,0.096777,0.443435,...,0.001284,0.001284,0.331745,0.647540,0.954819,0.000002,0.325021,0.263240,world/life,1.000000
2,6,johnnie ray,cry,1950,pop,sweetheart send letter goodbye secret feel bet...,24,0.002770,0.002770,0.002770,...,0.002770,0.225422,0.456298,0.585288,0.840361,0.000000,0.351814,0.139112,music,1.000000
3,10,p√©rez prado,patricia,1950,pop,kiss lips want stroll charm mambo chacha merin...,54,0.048249,0.001548,0.001548,...,0.225889,0.001548,0.686992,0.744404,0.083935,0.199393,0.775350,0.743736,romantic,1.000000
4,12,giorgos papadopoulos,apopse eida oneiro,1950,pop,till darling till matter know till dream live ...,48,0.001350,0.001350,0.417772,...,0.068800,0.001350,0.291671,0.646489,0.975904,0.000246,0.597073,0.394375,romantic,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28367,82447,mack 10,10 million ways,2019,hip hop,cause fuck leave scar tick tock clock come kno...,78,0.001350,0.001350,0.001350,...,0.065664,0.001350,0.889527,0.759711,0.062549,0.000000,0.751649,0.695686,obscene,0.014286
28368,82448,m.o.p.,ante up (robbin hoodz theory),2019,hip hop,minks things chain ring braclets yap fame come...,67,0.001284,0.001284,0.035338,...,0.001284,0.001284,0.662082,0.789580,0.004607,0.000002,0.922712,0.797791,obscene,0.014286
28369,82449,nine,whutcha want?,2019,hip hop,get ban get ban stick crack relax plan attack ...,77,0.001504,0.154302,0.168988,...,0.001504,0.001504,0.663165,0.726970,0.104417,0.000001,0.838211,0.767761,obscene,0.014286
28370,82450,will smith,switch,2019,hip hop,check check yeah yeah hear thing call switch g...,67,0.001196,0.001196,0.001196,...,0.001196,0.001196,0.883028,0.786888,0.007027,0.000503,0.508450,0.885882,obscene,0.014286
28371,82451,jeezy,r.i.p.,2019,hip hop,remix killer alive remix thriller trap bitch s...,83,0.001012,0.075202,0.001012,...,0.001012,0.033995,0.828875,0.674794,0.015862,0.000000,0.475474,0.492477,obscene,0.014286

In [4]:
very_big_dataset = big_dataset[["artist_name", "lyrics", "release_date"]]

In [ ]:
#df = big_dataset[big_dataset['release_date'] > 1994][["artist_name", "lyrics"]]

In [5]:
gender_df = pd.read_csv('singers_gender.csv')
female_artists = [x.lower() for x in gender_df[gender_df['gender'] == 'female']['artist'].to_list()]
male_artists = [x.lower() for x in gender_df[gender_df['gender'] == 'male']['artist'].to_list()]
len(female_artists), len(male_artists)

(7941, 15236)

In [6]:
df_selected_artists = pd.read_excel('eng_artists.xlsx', header=0)
#male_artists = df_selected_artists['men'].to_list()
female_artists.extend(df_selected_artists['women'].to_list())
female_artists = list(set(female_artists))
len(female_artists)

7952

In [7]:
male_artists.extend(df_selected_artists['men'].to_list())
male_artists = list(set(male_artists))

In [8]:
len(male_artists)

15256

In [9]:
male_df = very_big_dataset[very_big_dataset["artist_name"].isin(male_artists)]
fem_df = very_big_dataset[very_big_dataset["artist_name"].isin(female_artists)]

In [10]:
male_df['gender'] = 1
fem_df['gender'] = 0

C:\users\admin\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\users\admin\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [11]:
len(male_df.index), len(fem_df.index)

(8565, 2913)

In [12]:
sample_male_all = male_df.sample(2913)
sample_male_all

,artist_name,lyrics,release_date,gender
8914,dan fogelberg,past future unsure ask aware consequences drea...,1977,1
9627,earl thomas conley,say hard difference rise set feel change touch...,1984,1
2933,julio iglesias,need close eye want heartbeat away need hold h...,1983,1
9531,kenny rogers,reason help understand shelter rain end girl f...,1983,1
10906,tracy lawrence,hardest thing walk away love love somethings m...,1997,1
...,...,...,...,...
8433,graham nash,asleep kiss forehead give frown kiss start wak...,1971,1
12725,ray charles,tell people blackjack game cause trouble blame...,1958,1
9927,dwight yoakam,learn readin writin route job wait cities fact...,1987,1
8646,gram parsons,hearts bring misery hearts flame cold heart fr...,1974,1
21523,maxi priest,strollin strollin strollin girl hold hand feel...,1986,1

In [ ]:
def gendering(x, male_artists=male_artists, female_artists=female_artists):
    if x in male_artists:
        val = 1
    elif x in female_artists:
        val = 0
    else:
        val = 2
    return val

In [14]:
tc_sample_male = sample_male_all[['lyrics', 'gender']]
tc_fem_df = fem_df[['lyrics', 'gender']]
len(tc_sample_male), len(tc_fem_df)

(2913, 2913)

In [15]:
df_all = pd.concat([tc_sample_male, tc_fem_df])
df_all.groupby("gender").count()

        lyrics
gender
0         2913
1         2913

In [ ]:
#df_modern.to_csv("df_modern.csv", index=False)
#df_modern.to_csv("df_modern_indexed.csv")

In [16]:
df_all.to_csv("df_BIG.csv", index=False)